### ISSUE TITLE
Thoughts on adding a dark mode toggle for this theme

### ISSUE THREAD

**Issue by AsherThomasBabu** [gethugothemes/northendlab-light#15]
I wrote up some code for a dark mode toggle for this theme at the [CircuitVerse Blog](https://github.com/CircuitVerse/Blog/pull/101).
It was suggested by the maintainers there that I try adding the toggle directly upstream here.

I'd like to hear the maintainers views and suggestions on this and if so, can start working on a PR soon.

**Comment by tfsomrat** [comment]
Hello @AsherThomasBabu 

It will be great if you make a PR. it will help all Northendlab users.

**Comment by AsherThomasBabu** [comment]
@somratpro I'd like to know if the maintainers are in line with the idea, please provide your input on this issue.
Thanks

**Comment by mehedi-sharif** [comment]
Hey , 
Thanks for using our themes, and it's a great honor for us. I saw your blog and it seems very clean https://blog.circuitverse.org.  I am going to add your theme to our inspiration list. And also please make a PR obviously I will merge them in the repo. Have you ever checked our premium version of https://gethugothemes.com/products/northendlab/ . It has lots of features. You can migrate them if you want and I would love to give you a discount. But if you want to stick with the free version that is also great. As northendlab is free and released under MIT license it's not mandatory to add the credit but if you put the credits that inspire us a lot. 
Again thanks for creating with our product.
