### ISSUE TITLE
Documentation is missleading: Points to much of premium settings

### ISSUE THREAD

**Issue by Boldie** [gethugothemes/northendlab-light#20]
I tried for hours now to change the font settings from the linked doc page. After some time I gave up. It is really annoying to link docu which is not for this type of theme without any notice in it. Please add some markers which stuff is available only in your premium stuff and which not; not only in this lazy table here within the readme. You have a frustrated user now.

**Comment by tfsomrat** [comment]
Hello @Boldie 
We are sorry for this inconvenience, We mentioned in the table that "Color and fonts variable in config file" is not available. You have to understand the HTML and CSS to change the fonts. Or you can go with the premium version, which has much more features and is very easy to use. Hope you understand our perspective. Have a good day.
