### ISSUE TITLE
Is "Home Creative" available for free?

### ISSUE THREAD

**Issue by nataliepjlin** [gethugothemes/northendlab-light#21]
Is the template "home creative" in the live demo available on Github?

**Comment by tfsomrat** [comment]
Hello @nataliepjlin 

This is the free version of northendlab theme, here is the demo for it https://demo.gethugothemes.com/northendlab-light/

everything you can see here is available in this theme. but we also have a premium version of this theme, which has many more features including home-creative. If you want, you can purchase it from [here](https://gethugothemes.com/products/northendlab/)
